### ISSUE TITLE
Ruby 3.0 issue - wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by ptfly** [crazymanish/fastlane-plugin-slack_bot#4]
I'm having a crash when trying to use the plugin:

```
/usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-plugin-slack_bot-1.0.0/lib/fastlane/plugin/slack_bot/helper/slack_bot_link_formatter_helper.rb:41:in `initialize': \e[31m[!] wrong number of arguments (given 2, expected 1)\e[0m (ArgumentError)
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-plugin-slack_bot-1.0.0/lib/fastlane/plugin/slack_bot/helper/slack_bot_link_formatter_helper.rb:35:in `new'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-plugin-slack_bot-1.0.0/lib/fastlane/plugin/slack_bot/helper/slack_bot_link_formatter_helper.rb:35:in `format'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-plugin-slack_bot-1.0.0/lib/fastlane/plugin/slack_bot/actions/post_to_slack.rb:15:in `run'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:94:in `block in parsing_binding'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/gems/fastlane-2.188.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/bin/fastlane:23:in `load'
        from /usr/local/Cellar/fastlane/2.188.0/libexec/bin/fastlane:23:in `<main>'
```

Awesome plugin btw, thanks for sharing!!!

**Comment by crazymanish** [comment]
Hi @ptfly 

Can you share with me how you are calling the `post_to_slack ` action, so I can debug...it should not raise exception, nothing breaking was release in v2.188.0 🤔

**Comment by ptfly** [comment]
Nothing special, it was working before, may be some other dependency. Here is the implementation on my side:
```
    messageInstance = post_to_slack(
        channel: slackChannel,
        api_token: slackToken,
        username: slackUsername,
        icon_url: slackAvatar,
        pretext: "New App version is available for testing!",
        default_payloads: [:git_branch, :number_of_commits, :last_git_commit],
        payload: {
            "iOS:" => iosStoreLink,
            "Android:" => androidStoreLink,
            "Build Details:" => appPackage[:version] +" / "+ appPackage[:build],
        }
    )
```

**Comment by crazymanish** [comment]
Hi @ptfly 

Just tested with one message will all the above params, It is working for me...
I am requesting you to try one test slack message i.e see below

```ruby
post_to_slack(
        channel: slackChannel,
        api_token: slackToken,
        pretext: "This is a testing slack message", # testing slack message
        default_payloads: [:git_branch, :number_of_commits, :last_git_commit],
        payload: {
            "iOS:" => "iosStoreLink",
            "Android:" => "androidStoreLink",
            "Build Details:" => "appPackage[:version]" +" / "+ "appPackage[:build]",
        }
    )

**Comment by ptfly** [comment]
The exact same error. I even tried with just this:
```
    post_to_slack(
        channel: slackChannel,
        api_token: slackToken,
        pretext: "This is a testing slack message",
    )
```
No difference at all :(

**Comment by ptfly** [comment]
Ok, here is the fix, replacing this:
```
        # def initialize string, formats: %i[html markdown]
        #   @formats = formats
        #   @orig    = string.respond_to?(:scrub) ? string.scrub : string
        # end

        # This one works at least on my setup
        def initialize string, opts = {}
          @formats = opts[:formats] || %i[html markdown]
          @orig    = string.respond_to?(:scrub) ? string.scrub : string
        end
```

Found the fix here: https://github.com/slack-notifier/slack-notifier/issues/124#issuecomment-780124511

**Comment by crazymanish** [comment]
> Ok, here is the fix, replacing this:
> 
> ```
>         # def initialize string, formats: %i[html markdown]
>         #   @formats = formats
>         #   @orig    = string.respond_to?(:scrub) ? string.scrub : string
>         # end
> 
>         # This one works at least on my setup
>         def initialize string, opts = {}
>           @formats = opts[:formats] || %i[html markdown]
>           @orig    = string.respond_to?(:scrub) ? string.scrub : string
>         end
> ```
> 
> Found the fix here: [slack-notifier/slack-notifier#124 (comment)](https://github.com/slack-notifier/slack-notifier/issues/124#issuecomment-780124511)

Cool, but that is `Ruby 3.0.0` issue 🤔 and you are using Ruby2.6.3
Anyways, I am applying this patch, will release soon 😊

<img width="662" alt="Screenshot 2021-07-29 at 20 02 32" src="https://user-images.githubusercontent.com/5364500/127542836-b76dad10-eb6e-4d74-b956-c7c930c072be.png">

**Comment by ptfly** [comment]
Yes, its 3.0 but have no idea why its working.  Probably fastlane is using another ruby in a different context which I might have installed with something else. Have to check this thing out :)

**Comment by crazymanish** [comment]
Hi @ptfly 

Push the fix and release the new version 1.1.0...
https://rubygems.org/gems/fastlane-plugin-slack_bot/versions/1.1.0

You may need to run `bundle update fastlane-plugin-slack_bot` to use the latest version.
**can you please test** once? After your confirmation, I will close this bug. Thanks for finding the issue 👏

**Comment by ptfly** [comment]
Cant right now, not in front of a computer. Will test tmr and report back. Thanks for your cooperation!

**Comment by ptfly** [comment]
Works, thanks for the update!

**Comment by crazymanish** [comment]
Thanks, Closing this issue with git-commit https://github.com/crazymanish/fastlane-plugin-slack_bot/commit/54b0af0adeaaa54ab6a4fbc9cb470ffaa2041ee9 & release version [v1.1.0](https://github.com/crazymanish/fastlane-plugin-slack_bot/releases/tag/v1.1.0)
